### ISSUE TITLE
Add new keywords

### ISSUE THREAD

**Issue by xmatthewx** [mmmavis/docs-analyzer#12]
@KevZawacki - has a nice set of keywords for our issue areas. 

Let's add "keywords" and "runners-up" from this [doc](https://docs.google.com/document/d/1Tj3Pylsvs9DZcf-qr3CP0XF9vBPeEXYigTzbA5nkqvU/edit) to our filters.  No need to remove our existing words.

cc @mmmavis

**Comment by mmmavis** [comment]
fixed.
